# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Distribute new release

on:
  release:
    types: [created]


permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -n auto --cov=bigquery_exporter --cov-report=xml
  build:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist
  pypi-publish:
    needs: ['build']
    environment: 'release'
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/download-artifact@v4.1.7

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: artifact/

